version: '3.8'

services:
  rag-service:
    build:
      context: ./rag-service
      dockerfile: Dockerfile.gpu
    # To allow the container to access the GPU, add the following.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  indexing-service:
    build:
      context: ./indexing-service
      dockerfile: Dockerfile.gpu
    # To allow the container to access the GPU, add the following.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]