version: '3.8'

services:
  rag-service:
    build:
      context: ./rag-service
      dockerfile: Dockerfile.gpu
    # 컨테이너에 GPU 접근을 허용하려면 다음을 추가합니다.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  indexing-service:
    build:
      context: ./indexing-service
      dockerfile: Dockerfile.gpu
    # 컨테이너에 GPU 접근을 허용하려면 다음을 추가합니다.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
